
services:

    #PHP Service Laravel Application
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: ${DOCKER_APP_NAME}-app
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - ${DOCKER_APP_NAME}

    #mariadb
    mariadb:
        image: mariadb:10.8
        container_name: ${DOCKER_APP_NAME}-db
        restart: always
        environment:
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./docker/mariadb:/var/lib/mysql
        ports:
            - ${DB_CONTAINER_PORT}:${DB_PORT}
        networks:
            - ${DOCKER_APP_NAME}

    #Nginx Service
    nginx:
        image: nginx:1.17-alpine
        container_name: ${DOCKER_APP_NAME}-nginx
        restart: unless-stopped
        tty: true
        ports:
            - ${DOCKER_NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - ${DOCKER_APP_NAME}


networks:
    store:
        driver: bridge
